import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ['100', '300', '400', '700', '900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.variable}>
          <Provider>
            {children}
          </Provider>
      </body>
    </html>
  );
}
